application: baba-gallery
version: 1
runtime: python
api_version: 1

handlers:
# Script
- url: /artworks
  script: backend.py

- url: /artwork/.*
  script: backend.py

- url: /test
  script: backend.py

# Static
- url: /web
  static_dir: web

- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /(.*)
  static_files: public/\1
  upload: public/(.*)
