application: baba-gallery
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  script: main.py

- url: /test
  script: main.py

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: /artworks
  script: backend.py

- url: /artwork/.*
  script: backend.py
