application: baba-gallery
version: 2
runtime: python
api_version: 1

handlers:
# Script
- url: /artworks
  script: backend.py

- url: /artwork/.*
  script: backend.py

# Static
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /gallery
  static_files: public/gallery/frame.html
  upload: public/gallery/frame.html

- url: /painter
  static_files: public/painter/frame.html
  upload: public/painter/frame.html

- url: /(.*)
  static_files: public/\1
  upload: public/(.*)
